/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coding.meet.sampleopengenerator.code.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param title 
 * @param completed 
 */
@Serializable

data class Post (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "userId") @Required val userId: kotlin.Int,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "completed") val completed: kotlin.Boolean? = null

) {


}

